In [ ]:
import numpy as np
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

numpy arithmetic operations


In [ ]:
n= np.arange(10)
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a=n+n
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
b=n-n
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
m=n*n
m

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
d=n/n
d

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])