In [ ]:
import numpy as np
list=[1,2,3,4]
np.array(list)


array([1, 2, 3, 4])

In [ ]:
import numpy as np
list2=[[1,2,3],[2,1,3],[1,1,2]]
np.array(list2)







array([[1, 2, 3],
       [2, 1, 3],
       [1, 1, 2]])

In [ ]:
import numpy as np
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
import numpy as np
np.zeros(3)

array([0., 0., 0.])

In [ ]:
import numpy as np
np.zeros((5,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
import numpy as np
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
import numpy as np
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
import numpy as np
np.linspace(0,11,3)


array([ 0. ,  5.5, 11. ])

In [ ]:
import numpy as np
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [ ]:
import numpy as np
np.random.rand(20)


array([0.86693426, 0.22154582, 0.92190843, 0.97621991, 0.2607321 ,
       0.79181996, 0.28109623, 0.75633686, 0.2931279 , 0.45279405,
       0.72936983, 0.08791871, 0.08975821, 0.26870815, 0.20210111,
       0.65894863, 0.57489058, 0.87338686, 0.75801352, 0.82038037])

In [ ]:
import numpy as np
np.random.rand(5,5)

array([[0.4578422 , 0.45407171, 0.14037027, 0.20996102, 0.65799849],
       [0.89489157, 0.27252678, 0.14044572, 0.95375516, 0.34507616],
       [0.85023199, 0.80579089, 0.97009992, 0.62703003, 0.20291678],
       [0.58278451, 0.68772279, 0.5908991 , 0.5129685 , 0.71650913],
       [0.95386864, 0.59909619, 0.38565939, 0.22834402, 0.21237599]])

In [ ]:
import numpy as np
np.random.randn(7,5)

array([[ 0.01686955,  0.39993997, -1.46144873, -0.92948814,  0.9691076 ],
       [-0.1188221 , -0.01427539, -0.58388294, -2.07453237,  0.09995917],
       [ 0.70871901, -0.29827147, -1.25963057,  0.13932838,  0.11790414],
       [ 1.19973859, -1.9807397 , -0.77545743,  0.46533678, -1.14334568],
       [ 1.11421291, -2.06236284,  1.01947782, -0.74464748, -0.64964145],
       [-1.45402831,  0.37458063, -1.11946822,  0.43936759, -1.45837857],
       [ 0.87746297, -0.21431929,  0.41909028, -0.70797156, -0.00442427]])

In [ ]:
import numpy as np
np.random.randint(1,100)

67

In [ ]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
np.random.randint(1,100,11)

array([48, 21, 63, 97, 31, 96, 88, 17, 64, 52, 73])

In [ ]:
import numpy as np
a=np.random.rand(20)
a.reshape(5,4)


array([[0.51986833, 0.37150064, 0.2337934 , 0.53493424],
       [0.14982039, 0.85672271, 0.01099853, 0.97762309],
       [0.51471568, 0.29009164, 0.15862369, 0.0304231 ],
       [0.15803882, 0.48553675, 0.7518431 , 0.74513697],
       [0.35614582, 0.43030297, 0.96768973, 0.3236649 ]])

In [ ]:
a.max()

0.9776230941885315

In [ ]:
a.min()

0.010998526602094327

In [ ]:
a.shape

(20,)

In [ ]:
a.argmax()

7

In [ ]:
a.argmin()

6

In [ ]:
a.reshape(20,1).shape

(20, 1)

In [ ]:
a.reshape(20,1)

array([[0.51986833],
       [0.37150064],
       [0.2337934 ],
       [0.53493424],
       [0.14982039],
       [0.85672271],
       [0.01099853],
       [0.97762309],
       [0.51471568],
       [0.29009164],
       [0.15862369],
       [0.0304231 ],
       [0.15803882],
       [0.48553675],
       [0.7518431 ],
       [0.74513697],
       [0.35614582],
       [0.43030297],
       [0.96768973],
       [0.3236649 ]])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a[3]

0.5349342392889179

In [ ]:
arr=np.arange(25)

In [ ]:
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24])

In [ ]:

np.array(b)

array([4, 6, 1, 2, 3])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr[0:5]=100

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [ ]:
arr.reshape(5,5)

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [ ]:
arr=np.random.randint(1,100,25).reshape(5,5)
arr[0:2,0:2]=6
arr

array([[ 6,  6, 32, 65, 85],
       [ 6,  6, 37, 18, 87],
       [51, 23, 63, 34,  1],
       [99, 53, 89, 56, 67],
       [52, 76, 50, 32, 61]])

In [ ]:
arr[1,:]


array([ 6,  6, 37, 18, 87])

In [ ]:
arr[1:3,4]

array([87,  1])

In [ ]:
arr >7

array([[False, False,  True,  True,  True],
       [False, False,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
arr

array([[ 6,  6, 32, 65, 85],
       [ 6,  6, 37, 18, 87],
       [51, 23, 63, 34,  1],
       [99, 53, 89, 56, 67],
       [52, 76, 50, 32, 61]])

In [ ]:
arr[arr >7]

array([32, 65, 85, 37, 18, 87, 51, 23, 63, 34, 99, 53, 89, 56, 67, 52, 76,
       50, 32, 61])