In [1]:
import numpy as np
from numpy.linalg import svd

In [2]:
A = np.array([[1,2,3], [4,5,6], [5,7,9]])
U, S, VT = svd(A)

In [3]:
U

array([[-0.2354116 ,  0.78182354, -0.57735027],
       [-0.55937325, -0.5947842 , -0.57735027],
       [-0.79478485,  0.18703934,  0.57735027]])

In [4]:
S

array([1.56633231e+01, 8.12593979e-01, 1.13716384e-15])

In [5]:
VT

array([[-0.41158755, -0.56381288, -0.71603821],
       [-0.8148184 , -0.12429146,  0.56623547],
       [-0.40824829,  0.81649658, -0.40824829]])

In [6]:
a=(U @ np.diag(S) @ VT)

In [7]:
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [5., 7., 9.]])